### ISSUE TITLE
Compile error in "Conversions.h"

### ISSUE THREAD

**Issue by metabotics** [Greenroom-Robotics/rclUE#10]
@russkel 

It seems that 'Set' function is not defined yet. 
 
// ------------------------------------------------------------------------------------------------------------------------------//
template <typename T, typename ROSSequenceT>
inline void SetSequence(const T& in, ROSSequenceT &out) // TODO: change to be template param of TArray
{
if (out.data != nullptr)
{
	FMemory::Free(out.data);
}

out.data = (decltype(out.data)) FMemory::MallocZeroed(in.Num() * sizeof(decltype(*out.data)));

for (int i = 0; i < in.Num(); i++)
{
	Set(in[i], out.data[i]); **// error here**
}

out.size = in.Num();
out.capacity = in.Num();
}

**Comment by russkel** [comment]
Please post full compiler error. Set has been overloaded for ease of writing the Interface headers.
