### ISSUE TITLE
Blueprint example for this plugin

### ISSUE THREAD

**Issue by james-yoo** [Greenroom-Robotics/rclUE#2]
@russkel 
Nice work for integrating ROS2 and UE.
I would like to know how to setup blueprints for publishing simple topic using this plugin.

**Comment by russkel** [comment]
Hi @james-yoo 
I can't take a whole lot credit for that as it's a fork of https://github.com/rapyuta-robotics/rclUE. This one has deviated quite a lot from the original for various reasons. Writing some basic docs for this Plugin is on the todo list but I have other priorities at the moment. I'll try and get a screenshot of a basic publisher for you.

**Comment by james-yoo** [comment]
Hi @russkel 
Got it. Just screenshot is enough for testing a simple publisher or subscriber.

**Comment by james-yoo** [comment]
ping @russkel 
Please let me know if you ready to providea screenshot

**Comment by russkel** [comment]
Sorry about the delay. This fell off the radar. I don't have access to my files at the moment. Maybe I can explain briefly:

* A ROS2Node needs to be placed in the map, set `Initialise on Begin Play` to true to auto initialise.
* ROS2Publisher is an Actor Component that should be extended (create a child blueprint of the Publisher) and then added to Actors that you wish to publish values regarding. Lets call this `FloatPublisher` for example.
* In the FloatPublisher's blueprint On Begin Play, bind to the ROS2Node's `On Initialise` event and then using the Node's `AddPublisher` function add the FloatPublisher (self in the blueprint's context).
* Set important options of the FloatPublisher in the detail panel (QoS, topic name, Topic Type). Topic Type in this example will be UROS2Float32Msg. You can also use a built in timer to publish by enabling `Publish On Timer` and setting the `PublicationFrequencyHz`.


If you opted to use the `Publish On Timer`:
* "override" the `UpdateMessage` function in the FloatPublisher blueprint.
* The argument to this function is the pointer to the parent of the Topic Type, UROS2GenericMsg. Cast this to a `UROS2Float32Msg` and then set the `Data` member of this object to the float value you want. This blueprint will run every publish cycle.

If you didn't use the `Publish On Timer` option, things are a little bit less defined and you should consult the source code if you're unsure (ROS2Publisher.cpp isn't that long or complex). It's up to you if you want to do one of the following:

* A) Do the above and override UpdateMessage and then call the Publisher's `UpdateAndPublishMessage` function somewhere in your game. This is the function the inbuilt timer would have called in the above. This is the simplest way but can often not be what fits well in the blueprint.
* B) Call `Publish` directly. This will publish the `Topic Message` object of the Publisher component.
* C) Call `PublishMsg`, passing in an object of type `Topic Type`.

This maybe isn't super straightforward but I am fairly new to blueprints/Unreal so I don't know the gold standard way of implementing a Blueprint interface. If you think there is a far more elegant way please let me know.

**Comment by james-yoo** [comment]
Hi @russkel 
Thank you for your detailed explanation. I'll try.

**Comment by russkel** [comment]
I will try to get a screenshot tomorrow for you as well.

**Comment by james-yoo** [comment]
@russkel 
Any update regarding of screenshot?

**Comment by russkel** [comment]
Here is the basic publisher component that is a child class of Publisher:
![image](https://user-images.githubusercontent.com/1073606/165238869-c96f6f75-8f3b-4600-9008-a908082baabb.png)

Here is an actor that uses the component and its constructor.
![image](https://user-images.githubusercontent.com/1073606/165242235-05eff37e-194e-49df-a470-286ea4022180.png)

Same actor showing Begin Play
![image](https://user-images.githubusercontent.com/1073606/165243345-1c80377f-6297-42ad-be0b-f14ae24131e3.png)


It is a bit clunky and I do intend on adding automatic initialisation logic. Also any suggestions/mock ups of nice blueprints are appreciated.

**Comment by james-yoo** [comment]
@russkel Very nice! I will try.
